name: Merge version after bump

on:
  repository_dispatch:
    types: [publish-command]

jobs:
  live-merge:
    name: Merge live release

    runs-on: ubuntu-latest

    if: github.event.client_payload.slash_command.arg1 == 'release' && github.event.client_payload.pull_request.base.ref != 'live-release'

    steps:
      - name: Merge release
        uses: sudo-bot/action-pull-request-merge@v1.1.0
        with:
          github-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          number: ${{ github.event.client_payload.pull_request.number }}
          merge-method: merge
