name: Bump version

on:
  repository_dispatch:
    types: [release-command]

jobs:
  bump-version:
    name: Bump version

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: extension

    strategy:
      matrix:
        node: [13.3]

    steps:
      - name: Fail if release command did not specify preview as first argument
        if: github.event.client_payload.slash_command.arg1 != 'preview'
        uses: cutenode/action-always-fail@v1.0.1

      - name: Fail if release command does not target pre-release
        if: github.event.client_payload.pull_request.base.ref != 'pre-release'
        uses: cutenode/action-always-fail@v1.0.1

      - name: Fail if release command does not originate from master
        if: github.event.client_payload.pull_request.head.ref != 'master'
        uses: cutenode/action-always-fail@v1.0.1

      - name: Wait for CI
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Continuous Integration (13.3)
          ref: ${{ github.event.client_payload.github.payload.pull_request.head.ref }}

      - name: Notify about CI failure
        if: steps.wait-for-build.outputs.conclusion == 'failure'
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          edit-mode: append
          body: |
            > The CI Build failed. You'll need to fix any issues and re-run your command.

      - name: Fail
        if: steps.wait-for-build.outputs.conclusion == 'failure'
        uses: cutenode/action-always-fail@v1.0.1

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.github.payload.pull_request.head.ref }}

      - name: Use node ${{ matrix.node-version  }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version  }}

      - name: Bump version
        id: bump_version
        run: |
          VERSION=$(make bump step=${{ github.event.client_payload.slash_command.arg2 }})
          echo "::set-output name=version::$VERSION"

      - name: Create version bump commit
        uses: EndBug/add-and-commit@v4.1.0
        with:
          add: extension/package*
          author_email: 22681175+ktxtr-ci@users.noreply.github.com
          author_name: ktxtr-ci[bot]
          message: Bump version to ${{ steps.bump_version.outputs.version }}
          ref: ${{ github.event.client_payload.github.payload.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Allow merge
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          labels: version-ready
          number: ${{ github.event.client_payload.github.payload.issue.number }}

      - name: Notify about success
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          edit-mode: append
          body: |
            > Version Bump complete - Watch out for the release!
